        version: "3.9"
        services:
          db:
            image: postgres:14
            restart: always
            environment:
              POSTGRES_USER: shadowofcold
              POSTGRES_PASSWORD: 123
              POSTGRES_DB: cooking_recipes_db
            ports:
              - "5432:5432"
            volumes:
              - db_data:/var/lib/postgresql/data
        volumes:
          db_data:
