# Generated by Django 5.2 on 2025-05-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipeingredient_recipe_ingredient_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rating_average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
