# Generated by Django 5.2 on 2025-05-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_rating_average_recipe_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='steps_text',
            field=models.TextField(blank=True, null=True, verbose_name='Шаги рецепта'),
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
